package es.algonz.domain;

// Generated 20-jul-2013 18:00:15 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado", catalog = "algonz")
public class EstadoVO implements java.io.Serializable {

	private Integer cnEstado;
	private String teEstado;
	private Set<ActuacionVO> actuaciones = new HashSet<ActuacionVO>(0);
	private Set<AvisoEmpresaVO> avisoEmpresas = new HashSet<AvisoEmpresaVO>(0);

	public EstadoVO() {
	}

	public EstadoVO(Integer cnEstado, String teEstado) {
		this.cnEstado = cnEstado;
		this.teEstado = teEstado;
	}

	public EstadoVO(Integer cnEstado, String teEstado, Set<ActuacionVO> actuaciones,
			Set<AvisoEmpresaVO> avisoEmpresas) {
		this.cnEstado = cnEstado;
		this.teEstado = teEstado;
		this.actuaciones = actuaciones;
		this.avisoEmpresas = avisoEmpresas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CN_ESTADO", unique = true, nullable = false)
	public Integer getCnEstado() {
		return this.cnEstado;
	}

	public void setCnEstado(Integer cnEstado) {
		this.cnEstado = cnEstado;
	}

	@Column(name = "TE_ESTADO", nullable = false, length = 50)
	public String getTeEstado() {
		return this.teEstado;
	}

	public void setTeEstado(String teEstado) {
		this.teEstado = teEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<ActuacionVO> getActuaciones() {
		return this.actuaciones;
	}

	public void setActuaciones(Set<ActuacionVO> actuaciones) {
		this.actuaciones = actuaciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<AvisoEmpresaVO> getAvisoEmpresas() {
		return this.avisoEmpresas;
	}

	public void setAvisoEmpresas(Set<AvisoEmpresaVO> avisoEmpresas) {
		this.avisoEmpresas = avisoEmpresas;
	}

}
