package es.algonz.domain;

// Generated 20-jul-2013 18:00:15 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Siniestro generated by hbm2java
 */
@Entity
@Table(name = "siniestro", catalog = "algonz")
public class SiniestroVO implements java.io.Serializable {

	private Integer cnSiniestro;
	private PortalVO portal;
	private EmpresaComunidadVO empresaComunidad;
	private String teNombre;
	private String teObservaciones;
	private Set<ActuacionVO> actuacions = new HashSet<ActuacionVO>(0);
	private Set<DocumentoVO> documentos = new HashSet<DocumentoVO>(0);

	public SiniestroVO() {
	}

	public SiniestroVO(Integer cnSiniestro, PortalVO portal,
			EmpresaComunidadVO empresaComunidad) {
		this.cnSiniestro = cnSiniestro;
		this.portal = portal;
		this.empresaComunidad = empresaComunidad;
	}

	public SiniestroVO(Integer cnSiniestro, PortalVO portal,
			EmpresaComunidadVO empresaComunidad, String teNombre,
			String teObservaciones, Set<ActuacionVO> actuacions,
			Set<DocumentoVO> documentos) {
		this.cnSiniestro = cnSiniestro;
		this.portal = portal;
		this.empresaComunidad = empresaComunidad;
		this.teNombre = teNombre;
		this.teObservaciones = teObservaciones;
		this.actuacions = actuacions;
		this.documentos = documentos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CN_SINIESTRO", unique = true, nullable = false)
	public Integer getCnSiniestro() {
		return this.cnSiniestro;
	}

	public void setCnSiniestro(Integer cnSiniestro) {
		this.cnSiniestro = cnSiniestro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CN_PORTAL", nullable = false)
	public PortalVO getPortal() {
		return this.portal;
	}

	public void setPortal(PortalVO portal) {
		this.portal = portal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CN_EMPRESA_COMUNIDAD", nullable = false)
	public EmpresaComunidadVO getEmpresaComunidad() {
		return this.empresaComunidad;
	}

	public void setEmpresaComunidad(EmpresaComunidadVO empresaComunidad) {
		this.empresaComunidad = empresaComunidad;
	}

	@Column(name = "TE_NOMBRE", length = 50)
	public String getTeNombre() {
		return this.teNombre;
	}

	public void setTeNombre(String teNombre) {
		this.teNombre = teNombre;
	}

	@Column(name = "TE_OBSERVACIONES", length = 65535)
	public String getTeObservaciones() {
		return this.teObservaciones;
	}

	public void setTeObservaciones(String teObservaciones) {
		this.teObservaciones = teObservaciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "siniestro")
	public Set<ActuacionVO> getActuacions() {
		return this.actuacions;
	}

	public void setActuacions(Set<ActuacionVO> actuacions) {
		this.actuacions = actuacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "siniestro")
	public Set<DocumentoVO> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<DocumentoVO> documentos) {
		this.documentos = documentos;
	}

}
