
ALTER TABLE `algonz`.`usuario` ADD COLUMN `teNombre` VARCHAR(100) NULL  AFTER `PwdSistema` , ADD COLUMN `teApellido1` VARCHAR(100) NULL  AFTER `teNombre` , ADD COLUMN `teApellido2` VARCHAR(100) NULL  AFTER `teApellido1`, ADD COLUMN `teEmail` VARCHAR(50) NULL  AFTER `teApellido2` ;


drop table `algonz`.`consignatario`;


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

ALTER TABLE `algonz`.`usuario` CHANGE COLUMN `IdUsuario` `IdUsuario` INT(10) NOT NULL AUTO_INCREMENT  ;



/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
